name: safe_device
description: With the Flutter safe_device package, you can easily implement security steps such as Jailbroken, root, emulator and fake location detection.
version: 1.1.2
homepage: https://github.com/ufukhawk/safe_device

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
#  trust_location : ^2.0.13 #for mock location (for now)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.xamdesign.safe_device
        pluginClass: SafeDevicePlugin
      ios:
        pluginClass: SafeDevicePlugin
